/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.DataTransaksiController;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;


/**
 *
 * @author ASUS
 */
public class DataTransaksiView extends javax.swing.JFrame {
    
    DataTransaksiController controller = new DataTransaksiController();
    /**
     * Creates new form MainAdminView
     */
    public DataTransaksiView() {
        initComponents();
        headerdate();
        dcStart.setEnabled(false);
        dcEnd.setEnabled(false);
        controller.showTransaksi(tbTransaksi);
    }
    
    public void headerdate() {
        Date d = new Date();
        
        SimpleDateFormat sdf = new SimpleDateFormat("EEEE, dd MMM yyyy");
        String dd = sdf.format(d);
        lblDate.setText(dd);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NavBar_Main_Menu = new javax.swing.JPanel();
        lblDashboard = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblKelolaMenu = new javax.swing.JLabel();
        lblShiftment = new javax.swing.JLabel();
        lblPayroll = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        PanelDownloadLaporan = new javax.swing.JPanel();
        cbbPeriode = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnDownloadLaporan = new javax.swing.JButton();
        dcStart = new com.toedter.calendar.JDateChooser();
        dcEnd = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        Panel_Data = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTransaksi = new javax.swing.JTable();
        cbbFilterMetodePembayaran = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Transaksi");
        setBackground(new java.awt.Color(255, 255, 255));

        NavBar_Main_Menu.setBackground(new java.awt.Color(119, 31, 30));

        lblDashboard.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDashboard.setForeground(new java.awt.Color(255, 255, 255));
        lblDashboard.setText("Main Menu");
        lblDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDashboardMouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/HD_3-removebg-preview (2).png"))); // NOI18N
        jLabel7.setText("jLabel7");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("ServeUp");

        lblKelolaMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblKelolaMenu.setForeground(new java.awt.Color(255, 255, 255));
        lblKelolaMenu.setText("Pengelolaan Menu");
        lblKelolaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKelolaMenuMouseClicked(evt);
            }
        });

        lblShiftment.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblShiftment.setForeground(new java.awt.Color(255, 255, 255));
        lblShiftment.setText("Shiftment");
        lblShiftment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShiftmentMouseClicked(evt);
            }
        });

        lblPayroll.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPayroll.setForeground(new java.awt.Color(255, 255, 255));
        lblPayroll.setText("Payroll");
        lblPayroll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPayrollMouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Data Transaksi");

        lblUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("User");
        lblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserMouseClicked(evt);
            }
        });

        lblLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 255, 255));
        lblLogout.setText("Logout");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout NavBar_Main_MenuLayout = new javax.swing.GroupLayout(NavBar_Main_Menu);
        NavBar_Main_Menu.setLayout(NavBar_Main_MenuLayout);
        NavBar_Main_MenuLayout.setHorizontalGroup(
            NavBar_Main_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavBar_Main_MenuLayout.createSequentialGroup()
                .addGroup(NavBar_Main_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(NavBar_Main_MenuLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(NavBar_Main_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKelolaMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblShiftment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPayroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(NavBar_Main_MenuLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
        );
        NavBar_Main_MenuLayout.setVerticalGroup(
            NavBar_Main_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavBar_Main_MenuLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(NavBar_Main_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(65, 65, 65)
                .addComponent(lblDashboard)
                .addGap(34, 34, 34)
                .addComponent(lblKelolaMenu)
                .addGap(18, 18, 18)
                .addComponent(lblShiftment)
                .addGap(18, 18, 18)
                .addComponent(lblPayroll)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(lblUser)
                .addGap(251, 251, 251)
                .addComponent(lblLogout)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        Header.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(118, 119, 30));
        jLabel1.setText("Laporan Data Transaksi");

        lblDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(119, 31, 30));
        lblDate.setText("0");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDate)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        PanelDownloadLaporan.setBackground(new java.awt.Color(255, 255, 255));

        cbbPeriode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbbPeriode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Hari ini", "Kemarin", "7 Hari terakhir", "30 Hari terakhir", "Bulan lalu", "Custom" }));
        cbbPeriode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbPeriodeActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Pilih periode");

        btnDownloadLaporan.setBackground(new java.awt.Color(56, 93, 138));
        btnDownloadLaporan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDownloadLaporan.setForeground(new java.awt.Color(255, 255, 255));
        btnDownloadLaporan.setText("Download Laporan");
        btnDownloadLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadLaporanActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("-");

        javax.swing.GroupLayout PanelDownloadLaporanLayout = new javax.swing.GroupLayout(PanelDownloadLaporan);
        PanelDownloadLaporan.setLayout(PanelDownloadLaporanLayout);
        PanelDownloadLaporanLayout.setHorizontalGroup(
            PanelDownloadLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDownloadLaporanLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(PanelDownloadLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelDownloadLaporanLayout.createSequentialGroup()
                        .addComponent(cbbPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dcStart, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)
                        .addComponent(dcEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDownloadLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(508, Short.MAX_VALUE))
        );
        PanelDownloadLaporanLayout.setVerticalGroup(
            PanelDownloadLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDownloadLaporanLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDownloadLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDownloadLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(dcEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbbPeriode, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                        .addComponent(dcStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDownloadLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(39, 39, 39))
        );

        Panel_Data.setBackground(new java.awt.Color(255, 255, 255));

        tbTransaksi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Transaksi", "Tanggal Transaksi", "Total Bayar", "Email Pelanggan", "Metode Pembayaran"
            }
        ));
        jScrollPane1.setViewportView(tbTransaksi);

        cbbFilterMetodePembayaran.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbbFilterMetodePembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua metode pembayaran", "Cash", "Transfer", "Qris", "Kredit Card/ Debit Card" }));
        cbbFilterMetodePembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbFilterMetodePembayaranActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Metode Pembayaran");

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(166, 138, 31));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_DataLayout = new javax.swing.GroupLayout(Panel_Data);
        Panel_Data.setLayout(Panel_DataLayout);
        Panel_DataLayout.setHorizontalGroup(
            Panel_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DataLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(Panel_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Panel_DataLayout.createSequentialGroup()
                        .addComponent(cbbFilterMetodePembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1097, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        Panel_DataLayout.setVerticalGroup(
            Panel_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DataLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_DataLayout.createSequentialGroup()
                        .addGroup(Panel_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))
                    .addComponent(cbbFilterMetodePembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(NavBar_Main_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelDownloadLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel_Data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NavBar_Main_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelDownloadLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_Data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblKelolaMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKelolaMenuMouseClicked
        // TODO add your handling code here:
        PengelolaanMenuView view = new PengelolaanMenuView();
        view.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblKelolaMenuMouseClicked

    private void btnDownloadLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadLaporanActionPerformed
        // TODO add your handling code here:
        String periode = cbbPeriode.getSelectedItem().toString();
        LocalDate start = null;
        LocalDate end = null;

        if (periode.equalsIgnoreCase("Custom")) {
            Date startDate = dcStart.getDate();
            Date endDate = dcEnd.getDate();

            if (startDate == null || endDate == null) {
                JOptionPane.showMessageDialog(this, "Silakan pilih tanggal awal dan akhir terlebih dahulu.");
                return;
            }

            start = startDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            end = endDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            if (start.isAfter(end)) {
                JOptionPane.showMessageDialog(this, "Tanggal awal tidak boleh lebih dari tanggal akhir.");
                return;
            }
        }
        
        controller.exportPDF(this, periode, start, end);
    }//GEN-LAST:event_btnDownloadLaporanActionPerformed

    private void cbbPeriodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbPeriodeActionPerformed
        // TODO add your handling code here:
        String selected = cbbPeriode.getSelectedItem().toString();
        
        if (selected.equalsIgnoreCase("Custom")) {
            dcStart.setEnabled(true);
            dcEnd.setEnabled(true);
        } else {
            dcStart.setEnabled(false);
            dcEnd.setEnabled(false);
        }
    }//GEN-LAST:event_cbbPeriodeActionPerformed

    private void cbbFilterMetodePembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbFilterMetodePembayaranActionPerformed
        // TODO add your handling code here:
        controller.filterTransaksi(tbTransaksi, cbbFilterMetodePembayaran.getSelectedItem().toString());
    }//GEN-LAST:event_cbbFilterMetodePembayaranActionPerformed

    private void lblDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboardMouseClicked
        // TODO add your handling code here:
        MainAdminView view = new MainAdminView();
        view.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblDashboardMouseClicked

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin logout?", "Konfirmasi Logout", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            LoginView view = new LoginView();
            view.setVisible(true);
            this.dispose();
        } else if (confirm == JOptionPane.NO_OPTION) {

        }
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        // TODO add your handling code here:
        controller.searchTransaksi(tbTransaksi, txtSearch.getText());
    }//GEN-LAST:event_txtSearchKeyPressed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String searchStr = txtSearch.getText();
        if (searchStr.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Inputkan data yang ingin dicari");
            return;
        } else {
            controller.searchTransaksi(tbTransaksi, txtSearch.getText());
        }
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void lblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseClicked
        // TODO add your handling code here:
        PengelolaanUserView view = new PengelolaanUserView();
        view.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblUserMouseClicked

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void lblShiftmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShiftmentMouseClicked
        // TODO add your handling code here:
        PresensiView view = new PresensiView();
        view.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblShiftmentMouseClicked

    private void lblPayrollMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPayrollMouseClicked
        // TODO add your handling code here:
        PayrollView view = new PayrollView();
        view.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblPayrollMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataTransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataTransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataTransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataTransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataTransaksiView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel NavBar_Main_Menu;
    private javax.swing.JPanel PanelDownloadLaporan;
    private javax.swing.JPanel Panel_Data;
    private javax.swing.JButton btnDownloadLaporan;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbbFilterMetodePembayaran;
    private javax.swing.JComboBox<String> cbbPeriode;
    private com.toedter.calendar.JDateChooser dcEnd;
    private com.toedter.calendar.JDateChooser dcStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblKelolaMenu;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblPayroll;
    private javax.swing.JLabel lblShiftment;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTable tbTransaksi;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

}