/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.*;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import connection.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author ASUS
 */
public class ShiftmentView extends javax.swing.JFrame {

    ShiftmentController controller = new ShiftmentController();
    /**
     * Creates new form MainAdminView
     */
    public ShiftmentView() {
        initComponents();
        headerdate();
        controller.loadDataKaryawan(tbEmployee);
    }

    public void headerdate() {
        Date d = new Date();

        SimpleDateFormat sdf = new SimpleDateFormat("EEEE, dd MMM yyyy");
        String dd = sdf.format(d);
        lblDate.setText(dd);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NavBar_Main_Menu = new javax.swing.JPanel();
        lblMainMenu = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblPengelolaanMenu = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblPayroll = new javax.swing.JLabel();
        lblTransaksi = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cbbFilterHari = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbShiftPagi = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbShiftSore = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbbJadwalHari = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbbShiftKerja = new javax.swing.JComboBox<>();
        btnAddJadwal = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbEmployee = new javax.swing.JTable();
        txtSearchData = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnPresensi = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shiftment");
        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        NavBar_Main_Menu.setBackground(new java.awt.Color(119, 31, 30));
        NavBar_Main_Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NavBar_Main_MenuMousePressed(evt);
            }
        });

        lblMainMenu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMainMenu.setForeground(new java.awt.Color(255, 255, 255));
        lblMainMenu.setText("Main Menu");
        lblMainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMainMenuMouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/HD_3-removebg-preview (2).png"))); // NOI18N
        jLabel7.setText("jLabel7");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("ServeUp");

        lblPengelolaanMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPengelolaanMenu.setForeground(new java.awt.Color(255, 255, 255));
        lblPengelolaanMenu.setText("Pengelolaan Menu");
        lblPengelolaanMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPengelolaanMenuMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Shiftment");

        lblPayroll.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPayroll.setForeground(new java.awt.Color(255, 255, 255));
        lblPayroll.setText("Payroll");
        lblPayroll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPayrollMouseClicked(evt);
            }
        });

        lblTransaksi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        lblTransaksi.setText("Data Transaksi");
        lblTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTransaksiMouseClicked(evt);
            }
        });

        lblUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("User");
        lblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserMouseClicked(evt);
            }
        });

        lblLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 255, 255));
        lblLogout.setText("Logout");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout NavBar_Main_MenuLayout = new javax.swing.GroupLayout(NavBar_Main_Menu);
        NavBar_Main_Menu.setLayout(NavBar_Main_MenuLayout);
        NavBar_Main_MenuLayout.setHorizontalGroup(
            NavBar_Main_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavBar_Main_MenuLayout.createSequentialGroup()
                .addGroup(NavBar_Main_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(NavBar_Main_MenuLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(NavBar_Main_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPengelolaanMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPayroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(NavBar_Main_MenuLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
        );
        NavBar_Main_MenuLayout.setVerticalGroup(
            NavBar_Main_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavBar_Main_MenuLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(NavBar_Main_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(65, 65, 65)
                .addComponent(lblMainMenu)
                .addGap(34, 34, 34)
                .addComponent(lblPengelolaanMenu)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(lblPayroll)
                .addGap(18, 18, 18)
                .addComponent(lblTransaksi)
                .addGap(18, 18, 18)
                .addComponent(lblUser)
                .addGap(251, 251, 251)
                .addComponent(lblLogout)
                .addContainerGap(376, Short.MAX_VALUE))
        );

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(118, 119, 30));
        jLabel1.setText("Shiftment");

        lblDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(119, 31, 30));
        lblDate.setText("0");
        lblDate.setIconTextGap(1);

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1275, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDate)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1980, 1080));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        cbbFilterHari.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbbFilterHari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Hari", "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu" }));
        cbbFilterHari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbFilterHariActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Pilih Hari");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Jadwal Pagi");

        tbShiftPagi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbShiftPagi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Employee", "Nama", "Start Time", "End Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbShiftPagi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbShiftPagiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbShiftPagi);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Jadwal Sore");

        tbShiftSore.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbShiftSore.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Employee", "Nama", "Satrt Time", "End Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbShiftSore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbShiftSoreMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbShiftSore);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("ID Employee");

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIDKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Nama");

        txtNama.setMinimumSize(new java.awt.Dimension(64, 33));
        txtNama.setPreferredSize(new java.awt.Dimension(64, 33));
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Hari Kerja");

        cbbJadwalHari.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbbJadwalHari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Hari", "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu" }));
        cbbJadwalHari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbJadwalHariActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Shift");

        cbbShiftKerja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Shift", "Pagi", "Sore" }));

        btnAddJadwal.setBackground(new java.awt.Color(166, 138, 31));
        btnAddJadwal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddJadwal.setForeground(new java.awt.Color(255, 255, 255));
        btnAddJadwal.setText("Add Jadwal");
        btnAddJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddJadwalActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(56, 93, 138));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(158, 107, 67));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tbEmployee.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID Karyawan", "Nama Karawan"
            }
        ));
        tbEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbEmployeeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbEmployee);

        txtSearchData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchDataActionPerformed(evt);
            }
        });
        txtSearchData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchDataKeyPressed(evt);
            }
        });

        btnSearch.setText("Search");

        btnPresensi.setBackground(new java.awt.Color(56, 93, 138));
        btnPresensi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPresensi.setForeground(new java.awt.Color(255, 255, 255));
        btnPresensi.setText("Presensi Karyawan");
        btnPresensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPresensiActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(102, 0, 0));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbbFilterHari, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPresensi))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(386, 386, 386))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtNama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtID, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(btnAddJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(cbbShiftKerja, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbbJadwalHari, javax.swing.GroupLayout.Alignment.LEADING, 0, 516, Short.MAX_VALUE))
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSearchData, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(531, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbFilterHari, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPresensi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(txtSearchData)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbJadwalHari, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbShiftKerja, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(290, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(NavBar_Main_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1657, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NavBar_Main_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 927, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMainMenuMouseClicked
        // TODO add your handling code here:
        MainAdminView admin = new MainAdminView();
        admin.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblMainMenuMouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:  
        Component clicked = SwingUtilities.getDeepestComponentAt(jPanel1, evt.getX(), evt.getY());

        if (clicked != null && clicked != tbShiftPagi && !SwingUtilities.isDescendingFrom(clicked, tbShiftPagi)) {
            resetForm();
        } else if (clicked != null && clicked != tbShiftSore && !SwingUtilities.isDescendingFrom(clicked, tbShiftSore)) {
            resetForm();
        }
    }//GEN-LAST:event_jPanel1MousePressed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formMousePressed

    private void NavBar_Main_MenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavBar_Main_MenuMousePressed
        // TODO add your handling code here:
        Component clicked = SwingUtilities.getDeepestComponentAt(jPanel1, evt.getX(), evt.getY());

        if (clicked != null && clicked != tbShiftPagi && !SwingUtilities.isDescendingFrom(clicked, tbShiftPagi)) {
            resetForm();
        } else if (clicked != null && clicked != tbShiftSore && !SwingUtilities.isDescendingFrom(clicked, tbShiftSore)) {
            resetForm();
        }
    }//GEN-LAST:event_NavBar_Main_MenuMousePressed

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        // TODO add your handling code here:
        Component clicked = SwingUtilities.getDeepestComponentAt(jPanel1, evt.getX(), evt.getY());

        if (clicked != null && clicked != tbShiftPagi && !SwingUtilities.isDescendingFrom(clicked, tbShiftPagi)) {
            resetForm();
        } else if (clicked != null && clicked != tbShiftSore && !SwingUtilities.isDescendingFrom(clicked, tbShiftSore)) {
            resetForm();
        }
    }//GEN-LAST:event_HeaderMousePressed

    private void txtSearchDataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchDataKeyPressed
        // TODO add your handling code here:
        controller.searchUser(tbEmployee, txtSearchData.getText());
    }//GEN-LAST:event_txtSearchDataKeyPressed

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin logout?", "Konfirmasi Logout", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            LoginView view = new LoginView();
            view.setVisible(true);
            this.dispose();
        } else if (confirm == JOptionPane.NO_OPTION) {

        }
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void lblTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTransaksiMouseClicked
        // TODO add your handling code here:
        DataTransaksiView view = new DataTransaksiView();
        view.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblTransaksiMouseClicked

    private void lblPengelolaanMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPengelolaanMenuMouseClicked
        // TODO add your handling code here:
        PengelolaanMenuView view = new PengelolaanMenuView();
        view.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblPengelolaanMenuMouseClicked

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void cbbJadwalHariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbJadwalHariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbJadwalHariActionPerformed

    private void cbbFilterHariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbFilterHariActionPerformed
        // TODO add your handling code here:
        String scHari = cbbFilterHari.getSelectedItem().toString();
        controller.loadFilterJadwalShift(scHari, tbShiftPagi, "Pagi");
        controller.loadFilterJadwalShift(scHari, tbShiftSore, "Sore");
    }//GEN-LAST:event_cbbFilterHariActionPerformed

    private void tbShiftPagiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbShiftPagiMouseClicked
        // TODO add your handling code here:
        int selectedRow = tbShiftPagi.getSelectedRow();
        if (selectedRow >= 0) {
            String id_emp = tbShiftPagi.getValueAt(selectedRow, 0).toString();
            String nama = tbShiftPagi.getValueAt(selectedRow, 1).toString();

            txtID.setText(id_emp);
            txtNama.setText(nama);

            // Ambil hari & shift dari DB
            String sql = "SELECT h.nama_hari, s.shift "
                    + "FROM tb_shift_schedulling ss "
                    + "JOIN tb_shifts s ON ss.id_shifts = s.id_shifts "
                    + "JOIN tb_hari h ON s.id_hari = h.id_hari "
                    + "WHERE ss.id_employee = ? AND s.shift = 'Pagi'"; // karena ini tabel Shift Pagi

            try (Connection con = koneksi.getConnection(); PreparedStatement ps = con.prepareStatement(sql)) {

                ps.setString(1, id_emp);
                ResultSet rs = ps.executeQuery();

                if (rs.next()) {
                    String namaHari = rs.getString("nama_hari");
                    String shift = rs.getString("shift");

                    cbbJadwalHari.setSelectedItem(namaHari);
                    cbbShiftKerja.setSelectedItem(shift);
                }

            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Gagal ambil data shift: " + e.getMessage());
            }
        }

        txtID.setEnabled(false);
        txtNama.setEnabled(false);
    }//GEN-LAST:event_tbShiftPagiMouseClicked

    private void tbShiftSoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbShiftSoreMouseClicked
        // TODO add your handling code here:
        int selectedRow = tbShiftSore.getSelectedRow();
        if (selectedRow >= 0) {
            String id_emp = tbShiftSore.getValueAt(selectedRow, 0).toString();
            String nama = tbShiftSore.getValueAt(selectedRow, 1).toString();

            txtID.setText(id_emp);
            txtNama.setText(nama);

            // Ambil hari & shift dari DB
            String sql = "SELECT h.nama_hari, s.shift "
                    + "FROM tb_shift_schedulling ss "
                    + "JOIN tb_shifts s ON ss.id_shifts = s.id_shifts "
                    + "JOIN tb_hari h ON s.id_hari = h.id_hari "
                    + "WHERE ss.id_employee = ? AND s.shift = 'Sore'"; // karena ini tabel Shift Pagi

            try (Connection con = koneksi.getConnection(); PreparedStatement ps = con.prepareStatement(sql)) {

                ps.setString(1, id_emp);
                ResultSet rs = ps.executeQuery();

                if (rs.next()) {
                    String namaHari = rs.getString("nama_hari");
                    String shift = rs.getString("shift");

                    cbbJadwalHari.setSelectedItem(namaHari);
                    cbbShiftKerja.setSelectedItem(shift);
                }

            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Gagal ambil data shift: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_tbShiftSoreMouseClicked

    private void txtIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyPressed
        // TODO add your handling code here:
        String sql = "SELECT nama FROM tb_user WHERE id_employee = ?";
        try (Connection con = koneksi.getConnection(); PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setString(1, txtID.getText());
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                txtNama.setText(rs.getString("nama"));
            } else {
                txtNama.setText("");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtIDKeyPressed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtSearchDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchDataActionPerformed

    private void lblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseClicked
        // TODO add your handling code here:
        PengelolaanUserView view = new PengelolaanUserView();
        view.setVisible(true);
        dispose();

    }//GEN-LAST:event_lblUserMouseClicked

    private void btnAddJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddJadwalActionPerformed
        // TODO add your handling code here:
        controller.addJadwalShift(txtID.getText(), cbbJadwalHari.getSelectedItem().toString(), cbbShiftKerja.getSelectedItem().toString());
        String scHari = cbbFilterHari.getSelectedItem().toString();
        controller.loadFilterJadwalShift(scHari, tbShiftPagi, "Pagi");
        controller.loadFilterJadwalShift(scHari, tbShiftSore, "Sore");

        txtID.setText("");
        txtNama.setText("");
        cbbJadwalHari.setSelectedIndex(0);
        cbbShiftKerja.setSelectedIndex(0);
    }//GEN-LAST:event_btnAddJadwalActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        controller.updateShift(txtID.getText(), cbbJadwalHari.getSelectedItem().toString(), cbbShiftKerja.getSelectedItem().toString());
        String scHari = cbbFilterHari.getSelectedItem().toString();
        controller.loadFilterJadwalShift(scHari, tbShiftPagi, "Pagi");
        controller.loadFilterJadwalShift(scHari, tbShiftSore, "Sore");

        txtID.setText("");
        txtNama.setText("");
        cbbJadwalHari.setSelectedIndex(0);
        cbbShiftKerja.setSelectedIndex(0);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnPresensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresensiActionPerformed
        // TODO add your handling code here:
        PresensiView view = new PresensiView();
        view.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPresensiActionPerformed

    private void tbEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEmployeeMouseClicked
        // TODO add your handling code here:
        int selectedRow = tbEmployee.getSelectedRow();
        if (selectedRow >= 0) {
            String id_emp = tbEmployee.getValueAt(selectedRow, 0).toString();
            String nama = tbEmployee.getValueAt(selectedRow, 1).toString();

            txtID.setText(id_emp);
            txtNama.setText(nama);
        }
    }//GEN-LAST:event_tbEmployeeMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        controller.deleteJadwalShift(txtID.getText(), cbbJadwalHari.getSelectedItem().toString(), cbbShiftKerja.getSelectedItem().toString());
        String scHari = cbbFilterHari.getSelectedItem().toString();
        controller.loadFilterJadwalShift(scHari, tbShiftPagi, "Pagi");
        controller.loadFilterJadwalShift(scHari, tbShiftSore, "Sore");

        txtID.setText("");
        txtNama.setText("");
        cbbJadwalHari.setSelectedIndex(0);
        cbbShiftKerja.setSelectedIndex(0);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void lblPayrollMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPayrollMouseClicked
        // TODO add your handling code here:
        PayrollView view = new PayrollView();
        view.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblPayrollMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShiftmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShiftmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShiftmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShiftmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShiftmentView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel NavBar_Main_Menu;
    private javax.swing.JButton btnAddJadwal;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnPresensi;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbbFilterHari;
    private javax.swing.JComboBox<String> cbbJadwalHari;
    private javax.swing.JComboBox<String> cbbShiftKerja;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblMainMenu;
    private javax.swing.JLabel lblPayroll;
    private javax.swing.JLabel lblPengelolaanMenu;
    private javax.swing.JLabel lblTransaksi;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTable tbEmployee;
    private javax.swing.JTable tbShiftPagi;
    private javax.swing.JTable tbShiftSore;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtSearchData;
    // End of variables declaration//GEN-END:variables

    private void resetForm() {
        txtID.setText("");
        txtNama.setText("");
        cbbJadwalHari.setSelectedIndex(0);
        cbbShiftKerja.setSelectedIndex(0);

        txtID.setEnabled(true);
        txtNama.setEnabled(true);
    }
    
    private void clearForm() {
        txtID.setText("");
        txtNama.setText("");
        txtID.setEnabled(true);
        txtNama.setEnabled(true);
        cbbJadwalHari.setSelectedIndex(0);
        cbbShiftKerja.setSelectedIndex(0);
    }
}
