/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.text.SimpleDateFormat;
import java.text.NumberFormat;
import java.util.Date;
import java.util.Locale;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

import controller.*;
import utils.*;

/**
 *
 * @author ASUS
 */
public class TransaksiView extends javax.swing.JFrame {

    TransaksiController controller = new TransaksiController();

    /**
     * Creates new form TransaksiView
     */
    public TransaksiView() {
        initComponents();
        headerdate();
        controller.tampilDataMenu(tbMenu);
        tampilDataItemTransaksi();
        txtUangBayar.setEnabled(false);
        txtUangKembalian.setEnabled(false);
    }

    public void headerdate() {
        Date d = new Date();

        SimpleDateFormat sdf = new SimpleDateFormat("EEEE, dd MMM yyyy");
        String dd = sdf.format(d);
        lblDate.setText(dd);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSearchMenu = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        Struk = new javax.swing.JPanel();
        FormStruk = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaFormStruk = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        txtTotalBayar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbbMetodePembayaran = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtUangBayar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtUangKembalian = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtEmailPelanggan = new javax.swing.JTextField();
        btnSaveTransaksi = new javax.swing.JButton();
        btnSendInvoice = new javax.swing.JButton();
        Menu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMenu = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtKodeMenu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNamaMenu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHargaMenu = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbItemTransaksi = new javax.swing.JTable();
        btnAddItem = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnRemoveItem = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        btnTotal = new javax.swing.JButton();
        btnClearReceipt = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnUpdateItem = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POS ServeUp");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1980, 1080));

        Header.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(118, 119, 30));
        jLabel1.setText("POS ServeUP");

        lblDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDate.setForeground(new java.awt.Color(119, 31, 30));
        lblDate.setText("0");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/HD 7 (1).jpeg"))); // NOI18N

        txtSearchMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearchMenu.setSelectionColor(new java.awt.Color(191, 166, 166));
        txtSearchMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchMenuActionPerformed(evt);
            }
        });
        txtSearchMenu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchMenuKeyPressed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(83, 83, 21));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSearchMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(HeaderLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDate))
                            .addComponent(jLabel2)))
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearchMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Struk.setBackground(new java.awt.Color(119, 31, 30));

        FormStruk.setBackground(new java.awt.Color(255, 255, 255));

        areaFormStruk.setColumns(20);
        areaFormStruk.setRows(5);
        jScrollPane3.setViewportView(areaFormStruk);

        javax.swing.GroupLayout FormStrukLayout = new javax.swing.GroupLayout(FormStruk);
        FormStruk.setLayout(FormStrukLayout);
        FormStrukLayout.setHorizontalGroup(
            FormStrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        FormStrukLayout.setVerticalGroup(
            FormStrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total Bayar");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Metode Pembayaran");

        cbbMetodePembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Metode Pembayaran", "Cash", "Transfer", "QRIS", "Kredit Card/ Debit Card" }));
        cbbMetodePembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMetodePembayaranActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Uang Kembalian");

        txtUangBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUangBayarActionPerformed(evt);
            }
        });
        txtUangBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUangBayarKeyPressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Uang Bayar");

        txtUangKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUangKembalianActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Email Pelanggan");

        txtEmailPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailPelangganActionPerformed(evt);
            }
        });

        btnSaveTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSaveTransaksi.setForeground(new java.awt.Color(119, 31, 30));
        btnSaveTransaksi.setText("Save");
        btnSaveTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveTransaksiActionPerformed(evt);
            }
        });

        btnSendInvoice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSendInvoice.setForeground(new java.awt.Color(119, 31, 30));
        btnSendInvoice.setText("Send Inovice");
        btnSendInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendInvoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StrukLayout = new javax.swing.GroupLayout(Struk);
        Struk.setLayout(StrukLayout);
        StrukLayout.setHorizontalGroup(
            StrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StrukLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(StrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FormStruk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(StrukLayout.createSequentialGroup()
                        .addGroup(StrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(StrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtEmailPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(StrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTotalBayar, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtUangBayar)))
                        .addGap(18, 18, 18)
                        .addGroup(StrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbbMetodePembayaran, 0, 206, Short.MAX_VALUE)
                            .addComponent(txtUangKembalian)
                            .addGroup(StrukLayout.createSequentialGroup()
                                .addGroup(StrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(StrukLayout.createSequentialGroup()
                                        .addComponent(btnSaveTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnSendInvoice)))
                                .addGap(0, 4, Short.MAX_VALUE)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        StrukLayout.setVerticalGroup(
            StrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StrukLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(FormStruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTotalBayar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(cbbMetodePembayaran))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUangBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUangKembalian))
                .addGap(14, 14, 14)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSendInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnSaveTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEmailPelanggan))
                .addGap(147, 147, 147))
        );

        Menu.setBackground(new java.awt.Color(255, 255, 255));

        tbMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Menu", "Nama Menu", "Deskripsi Menu", "Harga", "Status"
            }
        ));
        tbMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbMenu);

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(83, 83, 21));
        jLabel3.setText("Daftar Menu");

        jLabel4.setText("Kode Menu");

        txtKodeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeMenuActionPerformed(evt);
            }
        });
        txtKodeMenu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKodeMenuKeyPressed(evt);
            }
        });

        jLabel5.setText("Nama Menu");

        jLabel6.setText("Harga");

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(83, 83, 21));
        jLabel7.setText("Daftar Item Dibeli");

        tbItemTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID_Menu", "Nama Menu", "Harga", "Quantity", "Subtotal"
            }
        ));
        tbItemTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbItemTransaksiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbItemTransaksi);

        btnAddItem.setBackground(new java.awt.Color(166, 138, 31));
        btnAddItem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddItem.setForeground(new java.awt.Color(255, 255, 255));
        btnAddItem.setText("Add Item");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(158, 107, 67));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear Item");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnRemoveItem.setBackground(new java.awt.Color(119, 31, 30));
        btnRemoveItem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRemoveItem.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveItem.setText("Remove Item");
        btnRemoveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveItemActionPerformed(evt);
            }
        });

        jLabel8.setText("Quantity");

        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });

        btnTotal.setBackground(new java.awt.Color(166, 138, 31));
        btnTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTotal.setForeground(new java.awt.Color(255, 255, 255));
        btnTotal.setText("Total");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        btnClearReceipt.setBackground(new java.awt.Color(119, 31, 30));
        btnClearReceipt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClearReceipt.setForeground(new java.awt.Color(255, 255, 255));
        btnClearReceipt.setText("Clear Receipt");
        btnClearReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearReceiptActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(90, 22, 21));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnUpdateItem.setBackground(new java.awt.Color(56, 93, 138));
        btnUpdateItem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdateItem.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateItem.setText("Update Item");
        btnUpdateItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateItemActionPerformed(evt);
            }
        });

        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MenuLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(260, 260, 260)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MenuLayout.createSequentialGroup()
                                .addComponent(btnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnClearReceipt)
                                .addGap(18, 18, 18)
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(MenuLayout.createSequentialGroup()
                                    .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtKodeMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(MenuLayout.createSequentialGroup()
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(260, 260, 260)
                                            .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtHargaMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(171, 171, 171)
                                    .addComponent(btnRefresh))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 93, Short.MAX_VALUE))
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(MenuLayout.createSequentialGroup()
                                .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnUpdateItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNamaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MenuLayout.createSequentialGroup()
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRemoveItem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(MenuLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtHargaMenu))
                        .addGroup(MenuLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtKodeMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5))
                .addGap(7, 7, 7)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtQuantity)
                    .addComponent(txtNamaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUpdateItem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnClear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemoveItem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnClearReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Struk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Struk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 29, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchMenuActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        controller.cariDataMenu(tbMenu, txtSearchMenu.getText());
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        // TODO add your handling code here:
        controller.tambahItemTransaksi(txtKodeMenu.getText(), txtNamaMenu.getText(), txtHargaMenu.getText(), txtQuantity.getText(), tbItemTransaksi, txtKodeMenu, txtNamaMenu, txtHargaMenu, txtQuantity);
        areaFormStruk.setText("");
        controller.showInvoice(tbItemTransaksi, areaFormStruk);

    }//GEN-LAST:event_btnAddItemActionPerformed

    private void btnRemoveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveItemActionPerformed
        // TODO add your handling code here:
        removeSelectedItem();
        areaFormStruk.setText("");
        controller.showInvoice(tbItemTransaksi, areaFormStruk);
    }//GEN-LAST:event_btnRemoveItemActionPerformed

    private void txtKodeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeMenuActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void cbbMetodePembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMetodePembayaranActionPerformed
        // TODO add your handling code here:
        String selected = cbbMetodePembayaran.getSelectedItem().toString();

        if (selected.equalsIgnoreCase("Cash")) {
            txtUangBayar.setEnabled(true);
            txtUangKembalian.setEnabled(true);
        } else {
            txtUangBayar.setEnabled(false);
            txtUangKembalian.setEnabled(false);
            txtUangBayar.setText("");
            txtUangKembalian.setText("");
        }
    }//GEN-LAST:event_cbbMetodePembayaranActionPerformed

    private void txtSearchMenuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchMenuKeyPressed
        // TODO add your handling code here:
        controller.cariDataMenu(tbMenu, txtSearchMenu.getText());
    }//GEN-LAST:event_txtSearchMenuKeyPressed

    private void txtKodeMenuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKodeMenuKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            controller.tampilkanDetailMenu(txtKodeMenu, txtNamaMenu, txtHargaMenu);
        }
    }//GEN-LAST:event_txtKodeMenuKeyPressed

    private void tbMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMenuMouseClicked
        // TODO add your handling code here:
        int selectedRow = tbMenu.getSelectedRow();
        if (selectedRow >= 0) {
            String id_menu = tbMenu.getValueAt(selectedRow, 0).toString();
            String nama_menu = tbMenu.getValueAt(selectedRow, 1).toString();
            String harga_menu = tbMenu.getValueAt(selectedRow, 3).toString();
            String status = tbMenu.getValueAt(selectedRow, 4).toString();

            if (status.equalsIgnoreCase("Tidak Tersedia")) {
                JOptionPane.showMessageDialog(null, "Menu ini tidak tersedia saat ini.", "Menu Tidak Tersedia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            txtKodeMenu.setText(id_menu);
            txtNamaMenu.setText(nama_menu);
            txtHargaMenu.setText(harga_menu);
            txtQuantity.setText("");
            txtQuantity.requestFocus();
        }
    }//GEN-LAST:event_tbMenuMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearItemTransaksi();
        areaFormStruk.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        // TODO add your handling code here:
        controller.hitungTotalBayar(tbItemTransaksi, txtTotalBayar);
    }//GEN-LAST:event_btnTotalActionPerformed

    private void btnClearReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearReceiptActionPerformed
        // TODO add your handling code here:
        areaFormStruk.setText("");
    }//GEN-LAST:event_btnClearReceiptActionPerformed

    private void btnSendInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendInvoiceActionPerformed
        // TODO add your handling code here:
        String email = txtEmailPelanggan.getText();
        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Maaf tidak ada email tujuan!.");
        } else {
            String invoice = controller.generateInvoice(tbItemTransaksi);
            String kode = controller.getKodeTransaksiGlobal();

            controller.sendEmailInvoice(email, invoice, kode);
        }

    }//GEN-LAST:event_btnSendInvoiceActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin keluar?", "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            LoginView view = new LoginView();
            view.setVisible(true);
            dispose();
        } else if (confirm == JOptionPane.NO_OPTION) {

        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSaveTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveTransaksiActionPerformed
        // TODO add your handling code here:
        String emailPelanggan = txtEmailPelanggan.getText();
        
        String kodeTransaksiUntukSave = controller.getKodeTransaksiGlobal();
        String tanggalTransaksiUntukSave = controller.getTanggalTransaksiGlobal();

        // Validasi esensial: Pastikan data kunci dari controller tidak null
        if (kodeTransaksiUntukSave == null || tanggalTransaksiUntukSave == null || LoginSession.currentUser == null) {
            JOptionPane.showMessageDialog(this, "Data transaksi atau sesi pengguna belum lengkap. Pastikan struk sudah digenerate dan Anda sudah login.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Hentikan proses jika ada data yang null
        }

        if (emailPelanggan.isEmpty()) {
            int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menyimpan transaksi\ntanpa kirim email ke pelanggan?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                controller.saveTransaksi(
                        tbItemTransaksi,
                        txtTotalBayar.getText(),
                        cbbMetodePembayaran.getSelectedItem().toString(),
                        txtEmailPelanggan.getText(), // Akan mengirim string kosong ""
                        LoginSession.currentUser.getId_user(),
                        kodeTransaksiUntukSave,
                        tanggalTransaksiUntukSave
                );
                clearItemTransaksi();
                areaFormStruk.setText("");
                txtEmailPelanggan.setText("");
                txtKodeMenu.setText("");
                txtNamaMenu.setText("");
                txtHargaMenu.setText("");
                txtQuantity.setText("");
                cbbMetodePembayaran.setSelectedIndex(0);
            } else if (confirm == JOptionPane.NO_OPTION) {
                // Do nothing, biarkan user tetap di form
                return; // Hentikan proses penyimpanan
            }
        } else {
            controller.saveTransaksi(
                    tbItemTransaksi,
                    txtTotalBayar.getText(),
                    cbbMetodePembayaran.getSelectedItem().toString(),
                    txtEmailPelanggan.getText(), // Akan mengirim email yang diinput user
                    LoginSession.currentUser.getId_user(),
                    kodeTransaksiUntukSave,
                    tanggalTransaksiUntukSave
            );
            clearItemTransaksi();
            areaFormStruk.setText("");
            txtEmailPelanggan.setText("");
            txtKodeMenu.setText("");
            txtNamaMenu.setText("");
            txtHargaMenu.setText("");
            txtQuantity.setText("");
            cbbMetodePembayaran.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btnSaveTransaksiActionPerformed

    private void txtUangBayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUangBayarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            DefaultTableModel model = (DefaultTableModel) tbItemTransaksi.getModel();
            float total = 0;

            for (int i = 0; i < model.getRowCount(); i++) {
                float subtotal = Float.parseFloat(model.getValueAt(i, 4).toString());
                total += subtotal;
            }

            try {
                int bayar = Integer.parseInt(txtUangBayar.getText());
                float kembalian = bayar - total;

                if (kembalian < 0) {
                    JOptionPane.showMessageDialog(null, "Uang bayar kurang!");
                    txtUangKembalian.setText("");
                } else {
                    Locale localeID = new Locale("in", "ID");
                    NumberFormat rupiahFormat = NumberFormat.getCurrencyInstance(localeID);
                    String kembalianFormatted = rupiahFormat.format(kembalian);
                    txtUangKembalian.setText(String.valueOf(kembalianFormatted));
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Input uang bayar harus angka!");
            }
        }
    }//GEN-LAST:event_txtUangBayarKeyPressed

    private void txtUangKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUangKembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUangKembalianActionPerformed

    private void txtUangBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUangBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUangBayarActionPerformed

    private void txtEmailPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailPelangganActionPerformed

    private void tbItemTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbItemTransaksiMouseClicked
        // TODO add your handling code here:
        int selectedRow = tbItemTransaksi.getSelectedRow();
        if (selectedRow >= 0) {
            String id_menu = tbItemTransaksi.getValueAt(selectedRow, 0).toString();
            String nama_menu = tbItemTransaksi.getValueAt(selectedRow, 1).toString();
            String harga_menu = tbItemTransaksi.getValueAt(selectedRow, 2).toString();
            String qty_menu = tbItemTransaksi.getValueAt(selectedRow, 3).toString();

            txtKodeMenu.setText(id_menu);
            txtNamaMenu.setText(nama_menu);
            txtHargaMenu.setText(harga_menu);
            txtQuantity.setText(qty_menu);
        }
    }//GEN-LAST:event_tbItemTransaksiMouseClicked

    private void btnUpdateItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateItemActionPerformed
        // TODO add your handling code here:
        updateQtyItemTransaksi();
        areaFormStruk.setText("");
        controller.showInvoice(tbItemTransaksi, areaFormStruk);
    }//GEN-LAST:event_btnUpdateItemActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        controller.tampilDataMenu(tbMenu);
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FormStruk;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Struk;
    private javax.swing.JTextArea areaFormStruk;
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClearReceipt;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRemoveItem;
    private javax.swing.JButton btnSaveTransaksi;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSendInvoice;
    private javax.swing.JButton btnTotal;
    private javax.swing.JButton btnUpdateItem;
    private javax.swing.JComboBox<String> cbbMetodePembayaran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDate;
    private javax.swing.JTable tbItemTransaksi;
    private javax.swing.JTable tbMenu;
    private javax.swing.JTextField txtEmailPelanggan;
    private javax.swing.JTextField txtHargaMenu;
    private javax.swing.JTextField txtKodeMenu;
    private javax.swing.JTextField txtNamaMenu;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSearchMenu;
    private javax.swing.JTextField txtTotalBayar;
    private javax.swing.JTextField txtUangBayar;
    private javax.swing.JTextField txtUangKembalian;
    // End of variables declaration//GEN-END:variables
    private String kodeTransaksiGlobal;
    private String tanggalTransaksiGlobal;

    private void clearInputFields() {
        txtKodeMenu.setText("");
        txtNamaMenu.setText("");
        txtHargaMenu.setText("");
    }

    private void clearItemTransaksi() {
        DefaultTableModel model = (DefaultTableModel) tbItemTransaksi.getModel();
        model.setRowCount(0);

        txtTotalBayar.setText("");
        txtUangBayar.setText("");
        txtUangKembalian.setText("");
    }

    private void tampilDataItemTransaksi() {
        DefaultTableModel model = (DefaultTableModel) tbItemTransaksi.getModel();
        model.setRowCount(0);
    }

    private void removeSelectedItem() {
        int selectedRow = tbItemTransaksi.getSelectedRow();

        if (selectedRow != -1) {
            DefaultTableModel model = (DefaultTableModel) tbItemTransaksi.getModel();
            int confirm = JOptionPane.showConfirmDialog(this, "Yakin Ingin menghapus item ini?", "KOnfirmasi Hapus", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                model.removeRow(selectedRow);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Pilih item yang ingin dihapus terlebih dahulu.", "Tidak Ada Item Dipilih", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void updateQtyItemTransaksi() {
        int selectedRow = tbItemTransaksi.getSelectedRow();

        if (selectedRow != -1) {
            try {
                int newQty = Integer.parseInt(txtQuantity.getText());

                if (newQty <= 0) {
                    JOptionPane.showMessageDialog(this, "Qty harus lebih dari 0");
                    return;
                }

                int harga = Integer.parseInt(tbItemTransaksi.getValueAt(selectedRow, 2).toString());
                int newSubtotal = newQty * harga;

                tbItemTransaksi.setValueAt(newQty, selectedRow, 3);
                tbItemTransaksi.setValueAt(newSubtotal, selectedRow, 4);

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Quantity harus berupa angka!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Silahkan pilih item yang ingin diubah.");
        }
    }
}
